#version: '3.8'
#services:
#  app:
#    image: your-app-image
#    ports:
#      - "8080:8080"
#    environment:
#      - APP_BASE_URL=http://localhost:8080
#      - SPRING_MAIL_HOST=smtp.gmail.com
#      - SPRING_MAIL_PORT=587
#      - SPRING_MAIL_USERNAME=ajaditaoreed@gmail.com
#      - SPRING_MAIL_PASSWORD=omuf whby kcxx rsyc